In [3]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
# Data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [51]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
265362,Senior Data Analyst,Fulfillment Senior Data Analyst,"Porto, Portugal",via Empregos Trabajo.org,Full-time,False,Portugal,2023-04-02 07:16:31,False,False,Portugal,NaN,NaN,NaN,FARFETCH UK Limited,"['sql', 'bigquery', 'excel', 'tableau', 'looke...","{'analyst_tools': ['excel', 'tableau', 'looker..."
19561,Data Analyst,Data Analyst/Interpreter,Anywhere,via LinkedIn,Full-time,True,Poland,2023-12-05 13:15:38,False,False,Poland,NaN,NaN,NaN,Luxoft,NaN,NaN
431487,Senior Data Scientist,YAD-926 | Sr. Data Scientist (ML Ops),India,via Shine,Full-time,False,India,2023-11-26 16:32:28,False,False,India,NaN,NaN,NaN,Yash Technologies,"['java', 'python', 'r', 'sql', 'azure', 'gcp',...","{'analyst_tools': ['power bi', 'tableau'], 'cl..."
23306,Data Engineer,dbt Data Engineer,Anywhere,via LinkedIn,Full-time,True,Turkey,2023-10-10 13:30:32,False,False,Turkey,NaN,NaN,NaN,BlueCloud,"['sql', 'aws', 'azure', 'git']","{'cloud': ['aws', 'azure'], 'other': ['git'], ..."
70322,Data Analyst,Data Migration Analyst,Ireland,via Trabajo.org,Full-time,False,Ireland,2023-04-21 06:31:24,True,False,Ireland,NaN,NaN,NaN,The Talent Locker,['sql'],{'programming': ['sql']}

In [52]:
df.index

RangeIndex(start=0, stop=785741, step=1, name='job_index')

In [53]:
df.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [54]:
df.index.name

'job_index'

In [55]:
df.index.name = 'job_index'

In [56]:
df.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [57]:
df.index.dtype

dtype('int64')

In [58]:
df_india = df[df['job_location'] == 'India']

In [59]:
df_india.head(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,NaN,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
194,Data Analyst,Data Analyst,India,via BeBee India,Full-time,False,India,2023-06-20 13:11:10,False,False,India,NaN,NaN,NaN,QuEST Global Services Pte. Ltd,"['python', 'sql', 'excel', 'ms access', 'power...","{'analyst_tools': ['excel', 'ms access', 'powe..."
391,Data Scientist,Data Scientist,India,via LinkedIn,Full-time,False,India,2023-11-04 13:31:56,False,False,India,NaN,NaN,NaN,Magna International,"['azure', 'databricks', 'gdpr', 'power bi', 'u...","{'analyst_tools': ['power bi'], 'cloud': ['azu..."
470,Data Engineer,Data Engineer,India,via Jobaaj.com,Full-time,False,India,2023-11-23 13:15:19,True,False,India,NaN,NaN,NaN,GKN Automotive,NaN,NaN
691,Data Analyst,Data Analyst,India,via BeBee India,Full-time,False,India,2023-09-12 13:14:38,True,False,India,NaN,NaN,NaN,AOS,NaN,NaN

In [60]:
df_india.reset_index(inplace=True)

df_india.head(5)

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,NaN,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
1,194,Data Analyst,Data Analyst,India,via BeBee India,Full-time,False,India,2023-06-20 13:11:10,False,False,India,NaN,NaN,NaN,QuEST Global Services Pte. Ltd,"['python', 'sql', 'excel', 'ms access', 'power...","{'analyst_tools': ['excel', 'ms access', 'powe..."
2,391,Data Scientist,Data Scientist,India,via LinkedIn,Full-time,False,India,2023-11-04 13:31:56,False,False,India,NaN,NaN,NaN,Magna International,"['azure', 'databricks', 'gdpr', 'power bi', 'u...","{'analyst_tools': ['power bi'], 'cloud': ['azu..."
3,470,Data Engineer,Data Engineer,India,via Jobaaj.com,Full-time,False,India,2023-11-23 13:15:19,True,False,India,NaN,NaN,NaN,GKN Automotive,NaN,NaN
4,691,Data Analyst,Data Analyst,India,via BeBee India,Full-time,False,India,2023-09-12 13:14:38,True,False,India,NaN,NaN,NaN,AOS,NaN,NaN

In [61]:
df_india.set_index('job_index', inplace=True)

In [62]:
df_india

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
38,Data Analyst,Data Quality and Governance Analyst 1,India,via Trabajo.org,Full-time,False,India,2023-07-23 13:24:57,False,False,India,NaN,NaN,NaN,"Jones Lang LaSalle IP, Inc","['sql', 'python', 'databricks', 'power bi', 'e...","{'analyst_tools': ['power bi', 'excel', 'word'..."
194,Data Analyst,Data Analyst,India,via BeBee India,Full-time,False,India,2023-06-20 13:11:10,False,False,India,NaN,NaN,NaN,QuEST Global Services Pte. Ltd,"['python', 'sql', 'excel', 'ms access', 'power...","{'analyst_tools': ['excel', 'ms access', 'powe..."
391,Data Scientist,Data Scientist,India,via LinkedIn,Full-time,False,India,2023-11-04 13:31:56,False,False,India,NaN,NaN,NaN,Magna International,"['azure', 'databricks', 'gdpr', 'power bi', 'u...","{'analyst_tools': ['power bi'], 'cloud': ['azu..."
470,Data Engineer,Data Engineer,India,via Jobaaj.com,Full-time,False,India,2023-11-23 13:15:19,True,False,India,NaN,NaN,NaN,GKN Automotive,NaN,NaN
691,Data Analyst,Data Analyst,India,via BeBee India,Full-time,False,India,2023-09-12 13:14:38,True,False,India,NaN,NaN,NaN,AOS,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785712,Data Engineer,India - Collections Analyst II,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Varite India Private Limited,"['excel', 'flow']","{'analyst_tools': ['excel'], 'other': ['flow']}"
785715,Data Analyst,Amul Careers 2023 - Apply Online - Data Analys...,India,melalui Jobsleworld - Jobs In India - Job Vaca...,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,NaN,NaN,NaN,Amul,NaN,NaN
785716,Software Engineer,Application Support Analyst,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,CompuGroup Medical,"['c#', 'sql']","{'programming': ['c#', 'sql']}"
785718,Business Analyst,Senior Performance QA Analyst,India,melalui BeBee India,Pekerjaan tetap,False,India,2023-03-13 06:16:28,False,False,India,NaN,NaN,NaN,Diebold Nixdorf,NaN,NaN
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [65]:
median_pivot = df_india.pivot_table(values= 'salary_year_avg', index='job_title_short', aggfunc=['median','min','max'])
median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                 64800.00         43200.0        142025.0
Data Analyst                     77133.75         32400.0        119250.0
Data Engineer                   120500.00         43200.0        156500.0
Data Scientist                  162500.00         43200.0        204381.0
Machine Learning Engineer       152500.00         64800.0        183000.0
Senior Data Analyst             109079.25         64800.0        119250.0
Senior Data Engineer            153500.00         64800.0        181765.0
Senior Data Scientist           157500.00         64800.0        170575.0
Software Engineer                72000.00         59400.0        123000.0

In [66]:
median_pivot.sort_values(by=('median','salary_year_avg'), ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Data Scientist                  162500.00         43200.0        204381.0
Senior Data Scientist           157500.00         64800.0        170575.0
Senior Data Engineer            153500.00         64800.0        181765.0
Machine Learning Engineer       152500.00         64800.0        183000.0
Data Engineer                   120500.00         43200.0        156500.0
Senior Data Analyst             109079.25         64800.0        119250.0
Data Analyst                     77133.75         32400.0        119250.0
Software Engineer                72000.00         59400.0        123000.0
Business Analyst                 64800.00         43200.0        142025.0

In [68]:
median_pivot.sort_index(inplace=True)

median_pivot

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                 64800.00         43200.0        142025.0
Data Analyst                     77133.75         32400.0        119250.0
Data Engineer                   120500.00         43200.0        156500.0
Data Scientist                  162500.00         43200.0        204381.0
Machine Learning Engineer       152500.00         64800.0        183000.0
Senior Data Analyst             109079.25         64800.0        119250.0
Senior Data Engineer            153500.00         64800.0        181765.0
Senior Data Scientist           157500.00         64800.0        170575.0
Software Engineer                72000.00         59400.0        123000.0

In [69]:
median_pivot.sort_values(by='job_title_short', ascending=False)

                                   median             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Software Engineer                72000.00         59400.0        123000.0
Senior Data Scientist           157500.00         64800.0        170575.0
Senior Data Engineer            153500.00         64800.0        181765.0
Senior Data Analyst             109079.25         64800.0        119250.0
Machine Learning Engineer       152500.00         64800.0        183000.0
Data Scientist                  162500.00         43200.0        204381.0
Data Engineer                   120500.00         43200.0        156500.0
Data Analyst                     77133.75         32400.0        119250.0
Business Analyst                 64800.00         43200.0        142025.0